In [2]:

#7. Do a and b have the same size? How do you prove that in Python code?
#1. Import the NUMPY package under the name np.
import numpy as np
#2. Print the NUMPY version and the configuration.
print(np.version.version)
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))
#4. Print a.
print(a)
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))
#6. Print b.
print(b)
#7. Do a and b have the same size? How do you prove that in Python code?
if ((a.size)) == int((b.size)):
    print("They have the same shape")
else:
    print("They have different shape")
#8. Are you able to add a and b? Why or why not?
try:
    sum_ab = a + b
    print(sum_ab)
except:
    print("Dimmensions are not the same, so this print it an exception")
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b, (1,2,0))
print((c.shape))
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a + c
print(d)
#Its working because the shape is identical, although to make it possible I had to transpose it: row,column,dimmension into the transpose function



1.17.3
[[[0.83162816 0.30001047 0.88207074 0.01445766 0.1573991 ]
  [0.76781859 0.05998563 0.77073709 0.61544848 0.49181596]
  [0.67632618 0.92661652 0.80218323 0.67656708 0.68796031]]

 [[0.11555622 0.73974678 0.84082502 0.80115425 0.06325106]
  [0.18655374 0.50969828 0.69071419 0.49827166 0.99338568]
  [0.54473958 0.93099015 0.44249291 0.14806849 0.4102683 ]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
They have the same shape
Dimmensions are not the same, so this print it an exception
(2, 3, 5)
[[[1.83162816 1.30001047 1.88207074 1.01445766 1.1573991 ]
  [1.76781859 1.05998563 1.77073709 1.61544848 1.49181596]
  [1.67632618 1.92661652 1.80218323 1.67656708 1.68796031]]

 [[1.11555622 1.73974678 1.84082502 1.80115425 1.06325106]
  [1.18655374 1.50969828 1.69071419 1.49827166 1.99338568]
  [1.54473958 1.93099015 1.44249291 1.14806849 1.4102683 ]]]
[[[0.83162816 0.30001047 0.88207074 0.0144

In [3]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print(d)



[[[0.83162816 0.30001047 0.88207074 0.01445766 0.1573991 ]
  [0.76781859 0.05998563 0.77073709 0.61544848 0.49181596]
  [0.67632618 0.92661652 0.80218323 0.67656708 0.68796031]]

 [[0.11555622 0.73974678 0.84082502 0.80115425 0.06325106]
  [0.18655374 0.50969828 0.69071419 0.49827166 0.99338568]
  [0.54473958 0.93099015 0.44249291 0.14806849 0.4102683 ]]]
[[[1.83162816 1.30001047 1.88207074 1.01445766 1.1573991 ]
  [1.76781859 1.05998563 1.77073709 1.61544848 1.49181596]
  [1.67632618 1.92661652 1.80218323 1.67656708 1.68796031]]

 [[1.11555622 1.73974678 1.84082502 1.80115425 1.06325106]
  [1.18655374 1.50969828 1.69071419 1.49827166 1.99338568]
  [1.54473958 1.93099015 1.44249291 1.14806849 1.4102683 ]]]


In [21]:
e = a * c
print(e)
print("Aqui se divide")
print (c)

if e.all() == a.all():
    print("Si son iguales")
else:
    print("no son iguales")

print(e)


[[[0.83162816 0.30001047 0.88207074 0.01445766 0.1573991 ]
  [0.76781859 0.05998563 0.77073709 0.61544848 0.49181596]
  [0.67632618 0.92661652 0.80218323 0.67656708 0.68796031]]

 [[0.11555622 0.73974678 0.84082502 0.80115425 0.06325106]
  [0.18655374 0.50969828 0.69071419 0.49827166 0.99338568]
  [0.54473958 0.93099015 0.44249291 0.14806849 0.4102683 ]]]
Aqui se divide
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
Si son iguales
[[[0.83162816 0.30001047 0.88207074 0.01445766 0.1573991 ]
  [0.76781859 0.05998563 0.77073709 0.61544848 0.49181596]
  [0.67632618 0.92661652 0.80218323 0.67656708 0.68796031]]

 [[0.11555622 0.73974678 0.84082502 0.80115425 0.06325106]
  [0.18655374 0.50969828 0.69071419 0.49827166 0.99338568]
  [0.54473958 0.93099015 0.44249291 0.14806849 0.4102683 ]]]


In [8]:
d_max = np.mean(d)
print(d_max)
print(d)

1.5525580497849458
[[[1.83162816 1.30001047 1.88207074 1.01445766 1.1573991 ]
  [1.76781859 1.05998563 1.77073709 1.61544848 1.49181596]
  [1.67632618 1.92661652 1.80218323 1.67656708 1.68796031]]

 [[1.11555622 1.73974678 1.84082502 1.80115425 1.06325106]
  [1.18655374 1.50969828 1.69071419 1.49827166 1.99338568]
  [1.54473958 1.93099015 1.44249291 1.14806849 1.4102683 ]]]


In [7]:
d_mean = np.mean(d)
d_max = np.max(d)
d_min = np.min(d)



print(d_mean)
print(d_max)
print(d_min)


1.5525580497849458
1.9933856789109532
1.0144576573428996


In [48]:


d_mean = np.mean(d)
d_max = np.max(d)
d_min = np.min(d)

h =[]
for i in d:
    for j in i:
        for k in j:
            h.append(k)
            
print(f'Esta es la lista {h}')

print(f' Esta es la media: {d_mean}')
print(f' Este es el máximo: {d_max}')
print(f' Este es el mínimo: {d_min}')
            
result = []            
for i in h:
    if i > d_min and i < d_mean:
        result.append(25)
    elif i > d_mean and i < d_max:
        result.append(75)
    elif i == d_mean:
        result.append(50)
    elif i == d_min:
        result.append(0)
    elif i == d_max:
        result.append(100)

print(f'Esta es la primera: {result}')
    
                



#for i in f:
    #if i > np.mean(f):
        #k.append("50")



TypeError: only integer scalar arrays can be converted to a scalar index